# Generated by Django 5.1.7 on 2025-03-22 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_otp_phone_number_customuser_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_completed_financial_info',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_expenses', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_savings', models.DecimalField(decimal_places=2, max_digits=12)),
                ('existing_investments', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_debt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('financial_goals', models.TextField()),
                ('risk_tolerance', models.CharField(max_length=20)),
                ('investment_time_horizon', models.CharField(max_length=20)),
                ('investment_preferences', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
