# Generated by Django 5.1.7 on 2025-04-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_marketdata_userrecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFundData',
            fields=[
                ('scheme_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('scheme_name', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('symbol', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='userrecommendation',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrecommendation',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userrecommendation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userrecommendation',
            name='recommendation_type',
            field=models.CharField(choices=[('STOCKS', 'Stocks'), ('MUTUAL_FUNDS', 'Mutual Funds'), ('SIP', 'SIP'), ('FIXED_INCOME', 'Fixed Income')], default='STOCKS', max_length=50),
        ),
        migrations.AlterField(
            model_name='userrecommendation',
            name='recommendations',
            field=models.JSONField(default=dict),
        ),
    ]
