# Generated by Django 5.1.7 on 2025-04-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_hashtag_customuser_profile_picture_post_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='group_videos/'),
        ),
    ]
